@echo off
setlocal enabledelayedexpansion

REM ================================================================
REM  new-vhost.bat  <domain>  <phpversion>
REM
REM  Creates (relative to the stack root, i.e. this script's folder):
REM    projects\<domain>\public\index.php  (phpinfo stub)
REM    nginx-1.31.1\conf\sites\<domain>.conf
REM  Then reloads Nginx.
REM
REM  The generated vhost uses nginx-prefix-relative paths (root goes
REM  through the nginx-1.31.1\projects junction), so the stack keeps
REM  working no matter where the root folder lives.
REM
REM  For simple second-level .test domains  (e.g. myapp.test)
REM  the *.test wildcard cert is used automatically.
REM  For third-level domains  (e.g. api.mygroup.test)  you must
REM  generate an additional wildcard cert for *.mygroup.test
REM  and edit the ssl_certificate lines in the generated conf.
REM
REM  PHP version / port map:
REM    php74  ->  9074
REM    php82  ->  9082
REM    php85  ->  9085
REM ================================================================

set "ROOT=%~dp0"
set "ROOT=%ROOT:~0,-1%"

if "%~1"=="" goto usage
if "%~2"=="" goto usage

set "DOMAIN=%~1"
set "PHPVER=%~2"
set "PORT="

if /i "!PHPVER!"=="php74" set "PORT=9074"
if /i "!PHPVER!"=="php82" set "PORT=9082"
if /i "!PHPVER!"=="php85" set "PORT=9085"

if "!PORT!"=="" (
    echo ERROR: Unknown PHP version "!PHPVER!". Valid options: php74, php82, php85
    exit /b 1
)

set "PROJDIR=%ROOT%\projects\!DOMAIN!"
set "PUBDIR=!PROJDIR!\public"
set "CONFFILE=%ROOT%\nginx-1.31.1\conf\sites\!DOMAIN!.conf"

REM ---- Scaffold project directories ----
if not exist "!PUBDIR!" (
    mkdir "!PUBDIR!"
    echo Created : !PUBDIR!
) else (
    echo Exists  : !PUBDIR!
)

REM ---- Starter index.php ----
if not exist "!PUBDIR!\index.php" (
    echo ^<?php phpinfo(); > "!PUBDIR!\index.php"
    echo Created : !PUBDIR!\index.php
)

REM ---- Write Nginx vhost conf ----
REM Paths inside the conf are relative to the nginx prefix
REM (<stack-root>\nginx-1.31.1), so the conf itself is portable.
echo Writing : !CONFFILE!
(
echo # Auto-generated by new-vhost.bat
echo # Domain  : !DOMAIN!
echo # PHP     : !PHPVER! -^> 127.0.0.1:!PORT!
echo # Cert    : _wildcard.test  ^(edit below if using a sub-group domain^)
echo # Paths: root/logs are prefix-relative, certs are conf-relative.
echo(
echo server {
echo     listen       80;
echo     server_name  !DOMAIN!;
echo     return 301   https://$host$request_uri;
echo }
echo(
echo server {
echo     listen       443 ssl;
echo     server_name  !DOMAIN!;
echo(
echo     root   projects/!DOMAIN!/public;
echo     index  index.php index.html;
echo(
echo     ssl_certificate      certs/_wildcard.test.pem;
echo     ssl_certificate_key  certs/_wildcard.test-key.pem;
echo(
echo     access_log  logs/!DOMAIN!.access.log  main;
echo     error_log   logs/!DOMAIN!.error.log   warn;
echo(
echo     location / {
echo         try_files $uri $uri/ /index.php?$query_string;
echo     }
echo(
echo     location ~ \.php$ {
echo         try_files       $uri =404;
echo         fastcgi_pass    127.0.0.1:!PORT!;
echo         fastcgi_index   index.php;
echo         include         fastcgi_params;
echo         fastcgi_param   SCRIPT_FILENAME  $document_root$fastcgi_script_name;
echo         fastcgi_param   HTTPS            on;
echo     }
echo(
echo     location ~ /\. {
echo         deny all;
echo     }
echo }
) > "!CONFFILE!"

REM ---- Ensure the projects junction the vhost root resolves through ----
if not exist "%ROOT%\nginx-1.31.1\projects" mklink /J "%ROOT%\nginx-1.31.1\projects" "%ROOT%\projects" >nul

REM ---- Reload Nginx ----
echo Reloading Nginx ...
"%ROOT%\nginx-1.31.1\nginx.exe" -p "%ROOT%\nginx-1.31.1" -s reload

echo.
echo ================================================================
echo  Virtual host ready: https://!DOMAIN!
echo  PHP version : !PHPVER!  (port !PORT!)
echo  Web root    : !PUBDIR!
echo ================================================================
echo.
echo  Add this line to C:\Windows\System32\drivers\etc\hosts
echo  ^(open Notepad as Administrator, or run this bat as Admin^):
echo.
echo     127.0.0.1   !DOMAIN!
echo.
goto :eof

:usage
echo.
echo  Usage  : new-vhost.bat ^<domain^> ^<phpversion^>
echo  Example: new-vhost.bat myapp.test php82
echo.
echo  PHP versions:  php74 ^(port 9074^)  php82 ^(port 9082^)  php85 ^(port 9085^)
echo.
exit /b 1
