@echo off
setlocal enabledelayedexpansion

REM ================================================================
REM  new-vhost.bat  <domain>  <phpversion>
REM
REM  Creates (relative to the stack root, i.e. this script's folder):
REM    projects\<domain>\public\index.php  (phpinfo stub)
REM    <nginx-prefix>\conf\sites\<domain>.conf
REM  Then reloads Nginx.
REM
REM  The generated vhost uses nginx-prefix-relative paths (root goes
REM  through the <nginx-prefix>\projects junction), so the stack keeps
REM  working no matter where the root folder lives -- and no matter
REM  which nginx version is active, since the prefix does not move.
REM
REM  For simple second-level .test domains  (e.g. myapp.test)
REM  the *.test wildcard cert is used automatically.
REM  For third-level domains  (e.g. api.mygroup.test)  you must
REM  generate an additional wildcard cert for *.mygroup.test
REM  and edit the ssl_certificate lines in the generated conf.
REM
REM  PHP version / port map:  90 + the version digits, so
REM    php-7.4  ->  9074
REM    php-8.2  ->  9082
REM    php-8.5  ->  9085
REM  Any spelling of the version works: 8.5, 85, or php-8.5.
REM ================================================================

set "ROOT=%~dp0"
set "ROOT=%ROOT:~0,-1%"

if "%~1"=="" goto usage
if "%~2"=="" goto usage

set "DOMAIN=%~1"
set "PHPVER=%~2"

REM Resolve the version against what is actually installed rather than a list
REM baked into this script, and derive the port the way start.bat assigns it.
call :digits WANT "!PHPVER!"
set "PORT="
for /d %%D in ("%ROOT%\php\php-*") do (
    call :digits HAVE "%%~nxD"
    if /i "!HAVE!"=="!WANT!" (
        set "PHPVER=%%~nxD"
        set "PORT=90!HAVE!"
    )
)

if "!PORT!"=="" (
    echo ERROR: PHP "%~2" is not installed. Installed versions:
    for /d %%D in ("%ROOT%\php\php-*") do echo    %%~nxD
    exit /b 1
)

REM Same prefix/binary resolution as start.bat -- see the comment there.
set "NGX_PREFIX="
if exist "%ROOT%\nginx\conf\nginx.conf" set "NGX_PREFIX=%ROOT%\nginx"
if not defined NGX_PREFIX for /d %%D in ("%ROOT%\nginx-*") do if exist "%%D\conf\nginx.conf" set "NGX_PREFIX=%%D"

if not defined NGX_PREFIX (
    echo ERROR: no nginx prefix found ^(looked for conf\nginx.conf under
    echo        %ROOT%\nginx and %ROOT%\nginx-*^).
    exit /b 1
)

set "NGX_EXE="
if exist "!NGX_PREFIX!\current\nginx.exe" set "NGX_EXE=!NGX_PREFIX!\current\nginx.exe"
if not defined NGX_EXE if exist "!NGX_PREFIX!\nginx.exe" set "NGX_EXE=!NGX_PREFIX!\nginx.exe"
if not defined NGX_EXE for /d %%D in ("!NGX_PREFIX!\nginx-*") do if exist "%%D\nginx.exe" set "NGX_EXE=%%D\nginx.exe"

set "PROJDIR=%ROOT%\projects\!DOMAIN!"
set "PUBDIR=!PROJDIR!\public"
set "CONFFILE=!NGX_PREFIX!\conf\sites\!DOMAIN!.conf"

REM ---- Scaffold project directories ----
if not exist "!PUBDIR!" (
    mkdir "!PUBDIR!"
    echo Created : !PUBDIR!
) else (
    echo Exists  : !PUBDIR!
)

REM ---- Starter index.php ----
if not exist "!PUBDIR!\index.php" (
    echo ^<?php phpinfo(); > "!PUBDIR!\index.php"
    echo Created : !PUBDIR!\index.php
)

REM ---- Write Nginx vhost conf ----
REM Paths inside the conf are relative to the nginx prefix, so the conf
REM itself is portable and survives an nginx version switch untouched.
echo Writing : !CONFFILE!
(
echo # Auto-generated by new-vhost.bat
echo # Domain  : !DOMAIN!
echo # PHP     : !PHPVER! -^> 127.0.0.1:!PORT!
echo # Cert    : _wildcard.test  ^(edit below if using a sub-group domain^)
echo # Paths: root/logs are prefix-relative, certs are conf-relative.
echo(
echo server {
echo     listen       80;
echo     server_name  !DOMAIN!;
echo     return 301   https://$host$request_uri;
echo }
echo(
echo server {
echo     listen       443 ssl;
echo     server_name  !DOMAIN!;
echo(
echo     root   projects/!DOMAIN!/public;
echo     index  index.php index.html;
echo(
echo     ssl_certificate      certs/_wildcard.test.pem;
echo     ssl_certificate_key  certs/_wildcard.test-key.pem;
echo(
echo     access_log  logs/!DOMAIN!.access.log  main;
echo     error_log   logs/!DOMAIN!.error.log   warn;
echo(
echo     location / {
echo         try_files $uri $uri/ /index.php?$query_string;
echo     }
echo(
echo     location ~ \.php$ {
echo         try_files       $uri =404;
echo         fastcgi_pass    127.0.0.1:!PORT!;
echo         fastcgi_index   index.php;
echo         include         fastcgi_params;
echo         fastcgi_param   SCRIPT_FILENAME  $document_root$fastcgi_script_name;
echo         fastcgi_param   HTTPS            on;
echo     }
echo(
echo     location ~ /\. {
echo         deny all;
echo     }
echo }
) > "!CONFFILE!"

REM ---- Ensure the projects junction the vhost root resolves through ----
if not exist "!NGX_PREFIX!\projects" mklink /J "!NGX_PREFIX!\projects" "%ROOT%\projects" >nul

REM ---- Reload Nginx ----
if defined NGX_EXE (
    echo Reloading Nginx ...
    "!NGX_EXE!" -p "!NGX_PREFIX!" -s reload
) else (
    echo Skipping the reload - no nginx.exe found. The conf is written; it is
    echo picked up whenever nginx next starts.
)

echo.
echo ================================================================
echo  Virtual host ready: https://!DOMAIN!
echo  PHP version : !PHPVER!  (port !PORT!)
echo  Web root    : !PUBDIR!
echo ================================================================
echo.
echo  Add this line to C:\Windows\System32\drivers\etc\hosts
echo  ^(open Notepad as Administrator, or run this bat as Admin^):
echo.
echo     127.0.0.1   !DOMAIN!
echo.
goto :eof

:usage
echo.
echo  Usage  : new-vhost.bat ^<domain^> ^<phpversion^>
echo  Example: new-vhost.bat myapp.test 8.2
echo.
echo  Installed PHP versions ^(the FastCGI port is 90 + the digits^):
for /d %%D in ("%ROOT%\php\php-*") do echo    %%~nxD
echo.
exit /b 1

REM Reduce a version spelling to its digits: php-8.5 / 8.5 / 85 -^> 85
:digits
set "_D=%~2"
set "_D=%_D:.=%"
set "_D=%_D:php=%"
set "_D=%_D:-=%"
set "%~1=%_D%"
exit /b 0
