//! devcrate -- manage a portable, multi-PHP development stack for Windows.
//!
//! Two front ends over one core: the subcommands below, and the dashboard in
//! [`tui`] that runs when none is given. Every batch script in the stack root
//! has an equivalent in both, and `install` downloads and installs PHP, nginx,
//! Composer, PostgreSQL, and Python end to end. What is left of installing is
//! MariaDB, RabbitMQ, and Erlang.

mod cli;
mod config;
mod control;
mod install;
mod junction;
mod nginx;
mod php;
mod probe;
mod python;
mod root;
mod site;
mod status;
mod term;
mod tui;

use std::process::ExitCode;

use anyhow::Result;
use clap::Parser;

use crate::cli::{
    Cli, Command, ConfigCommand, NginxCommand, PhpCommand, PythonCommand, SiteCommand,
};
use crate::config::Stack;

/// Exit codes. 2 is clap's own code for a usage error. 3 used to mean "not
/// built yet, a batch script does this today"; nothing exits 3 any more, but
/// scripts written against it lose nothing by keeping the check.
pub mod exit {
    pub const OK: u8 = 0;
    pub const ERROR: u8 = 1;
}

fn main() -> ExitCode {
    let cli = Cli::parse();
    match run(cli) {
        Ok(code) => ExitCode::from(code),
        Err(err) => {
            eprintln!("devcrate: {err:#}");
            ExitCode::from(exit::ERROR)
        }
    }
}

fn run(cli: Cli) -> Result<u8> {
    let stack = Stack::open(root::resolve(cli.root)?)?;

    let Some(command) = cli.command else {
        return tui::run(stack);
    };

    match command {
        Command::Status(args) => {
            let report = status::report(&stack);
            if args.json {
                status::print_json(&report)?;
            } else {
                status::print_text(&report);
            }
            Ok(exit::OK)
        }

        Command::Config(ConfigCommand::Show) => {
            print!("{}", config_toml(&stack)?);
            Ok(exit::OK)
        }
        Command::Config(ConfigCommand::Path) => {
            println!("{}", stack.root.join(root::CONFIG_FILE).display());
            Ok(exit::OK)
        }

        Command::Php(PhpCommand::List) => {
            php_list(&stack);
            Ok(exit::OK)
        }
        Command::Php(PhpCommand::Use(args)) => php::switch(&stack, &args.version),

        Command::Python(PythonCommand::List) => python::list(&stack),
        Command::Python(PythonCommand::Use(args)) => python::switch(&stack, &args.version),

        Command::Nginx(NginxCommand::List) => nginx::list(&stack),
        Command::Nginx(NginxCommand::Use(args)) => nginx::switch(&stack, &args.version),
        Command::Nginx(NginxCommand::Migrate(args)) => {
            nginx::migrate_command(&stack, args.dry_run)
        }

        Command::Site(SiteCommand::List) => {
            site_list(&stack);
            Ok(exit::OK)
        }
        Command::Site(SiteCommand::Add(args)) => {
            site::add(&stack, &args.host, args.php.as_deref(), args.force)
        }
        Command::Site(SiteCommand::SetPhp(args)) => {
            site::set_php(&stack, &args.host, &args.version)
        }
        Command::Site(SiteCommand::Remove(args)) => site::remove(&stack, &args.host),

        Command::Start(args) => control::start(&stack, args.service.as_deref()),
        Command::Stop(args) => control::stop(&stack, args.service.as_deref()),
        Command::Restart(args) => control::restart(&stack, args.service.as_deref()),
        Command::Install(args) => install::install(
            &stack,
            &args.runtime,
            args.version.as_deref(),
            args.from.as_deref(),
            args.force,
        ),
    }
}

fn config_toml(stack: &Stack) -> Result<String> {
    let header = format!(
        "# Devcrate configuration for {}\n\
         # Generated by `devcrate config show` from the folder layout.\n\
         # Save this as devcrate.toml in the stack root to pin these values.\n\n",
        stack.root.display()
    );
    Ok(header + &toml::to_string_pretty(&stack.to_config())?)
}

fn php_list(stack: &Stack) {
    let current = stack.current_php();
    let current_name =
        current.as_ref().and_then(|p| p.file_name()).map(|n| n.to_string_lossy().into_owned());

    let services: Vec<_> = stack.php_services().collect();
    if services.is_empty() {
        println!("No PHP versions found in {}", stack.rel(&stack.php_dir));
        return;
    }

    let width = services.iter().map(|p| p.id.chars().count()).max().unwrap_or(0);
    for php in services {
        let is_current = current_name.as_deref() == Some(php.id.as_str());
        let active = if is_current { "*" } else { " " };
        let port = php.ports.first().map(|p| p.to_string()).unwrap_or_else(|| "-".into());
        let state = if php.is_installed() { "" } else { "  (php-cgi.exe missing)" };
        let row = format!(
            "{active} {:<8}  {:<width$}  fastcgi {port}{state}",
            php.name, php.id
        );
        match is_current {
            true => println!("{}", term::paint(&row, term::Color::Green)),
            false => println!("{row}"),
        }
    }

    match current_name {
        Some(name) => println!("\n* = php\\current -> {name} (what the CLI resolves to)"),
        None => println!("\nphp\\current is not set; run `devcrate php use 8.5` to create it"),
    }
}

fn site_list(stack: &Stack) {
    let confs = stack.sites();
    if confs.is_empty() {
        println!("No vhosts in {}", stack.rel(&stack.sites_dir()));
        return;
    }

    let sites: Vec<site::Site> = confs.iter().map(|c| site::Site::read(c)).collect();
    let width = sites.iter().map(|s| s.host.chars().count()).max().unwrap_or(0);

    for site in &sites {
        let php = site
            .fastcgi_port
            .map(|p| format!("php {p}"))
            .unwrap_or_else(|| "no fastcgi_pass".into());
        let root = site.root.as_deref().unwrap_or("no root directive");
        println!("  {:<width$}  {php:<10}  {root}", site.host);
    }
    println!("\n{} vhost(s) in {}", sites.len(), stack.rel(&stack.sites_dir()));
}
