//! devcrate -- manage a portable, multi-PHP development stack for Windows.
//!
//! This first cut is read-only. Everything that changes the stack is still done
//! by the batch scripts in the stack root; those commands are declared here so
//! the surface is fixed, and they say which script to run instead.

mod cli;
mod config;
mod probe;
mod root;
mod site;
mod status;

use std::process::ExitCode;

use anyhow::Result;
use clap::Parser;

use crate::cli::{Cli, Command, ConfigCommand, PhpCommand, SiteCommand};
use crate::config::Stack;

/// Exit codes. 2 is clap's own code for a usage error.
pub mod exit {
    pub const OK: u8 = 0;
    pub const ERROR: u8 = 1;
    pub const NOT_IMPLEMENTED: u8 = 3;
}

fn main() -> ExitCode {
    let cli = Cli::parse();
    match run(cli) {
        Ok(code) => ExitCode::from(code),
        Err(err) => {
            eprintln!("devcrate: {err:#}");
            ExitCode::from(exit::ERROR)
        }
    }
}

fn run(cli: Cli) -> Result<u8> {
    let stack = Stack::open(root::resolve(cli.root)?)?;

    match cli.command {
        Command::Status(args) => {
            let report = status::report(&stack);
            if args.json {
                status::print_json(&report)?;
            } else {
                status::print_text(&report);
            }
            Ok(exit::OK)
        }

        Command::Config(ConfigCommand::Show) => {
            print!("{}", config_toml(&stack)?);
            Ok(exit::OK)
        }
        Command::Config(ConfigCommand::Path) => {
            println!("{}", stack.root.join(root::CONFIG_FILE).display());
            Ok(exit::OK)
        }

        Command::Php(PhpCommand::List) => {
            php_list(&stack);
            Ok(exit::OK)
        }
        Command::Php(PhpCommand::Use(args)) => {
            Ok(todo_command(&format!("php use {}", args.version), "phpuse.bat"))
        }

        Command::Site(SiteCommand::List) => {
            site_list(&stack);
            Ok(exit::OK)
        }
        Command::Site(SiteCommand::Add(args)) => {
            Ok(todo_command(&format!("site add {}", args.host), "new-vhost.bat"))
        }
        Command::Site(SiteCommand::Remove(args)) => Ok(todo_command(
            &format!("site remove {}", args.host),
            "manual removal: delete the conf under nginx conf\\sites, then reload nginx",
        )),

        Command::Start(_) => Ok(todo_command("start", "start.bat")),
        Command::Stop(_) => Ok(todo_command("stop", "stop.bat")),
        Command::Restart(_) => Ok(todo_command("restart", "stop.bat, then start.bat")),
        Command::Install(args) => {
            Ok(todo_command(&format!("install {}", args.runtime), "docs/installation.md"))
        }
    }
}

/// Say plainly that a command is declared but not built, and point at what does
/// the job today. Never silently do nothing.
fn todo_command(what: &str, instead: &str) -> u8 {
    eprintln!("devcrate {what}: not implemented yet.");
    eprintln!("Use {instead} for now.");
    exit::NOT_IMPLEMENTED
}

fn config_toml(stack: &Stack) -> Result<String> {
    let header = format!(
        "# Devcrate configuration for {}\n\
         # Generated by `devcrate config show` from the folder layout.\n\
         # Save this as devcrate.toml in the stack root to pin these values.\n\n",
        stack.root.display()
    );
    Ok(header + &toml::to_string_pretty(&stack.to_config())?)
}

fn php_list(stack: &Stack) {
    let current = stack.current_php();
    let current_name =
        current.as_ref().and_then(|p| p.file_name()).map(|n| n.to_string_lossy().into_owned());

    let services: Vec<_> = stack.php_services().collect();
    if services.is_empty() {
        println!("No PHP versions found in {}", stack.rel(&stack.php_dir));
        return;
    }

    for php in services {
        let active = if current_name.as_deref() == Some(php.id.as_str()) { "*" } else { " " };
        let port = php.ports.first().map(|p| p.to_string()).unwrap_or_else(|| "-".into());
        let state = if php.is_installed() { "" } else { "  (php-cgi.exe missing)" };
        println!("{active} {:<8}  {:<6}  fastcgi {port}{state}", php.name, php.id);
    }

    match current_name {
        Some(name) => println!("\n* = php\\current -> {name} (what the CLI resolves to)"),
        None => println!("\nphp\\current is not set; run `phpuse 85` to create it"),
    }
}

fn site_list(stack: &Stack) {
    let confs = stack.sites();
    if confs.is_empty() {
        println!("No vhosts in {}", stack.rel(&stack.sites_dir()));
        return;
    }

    let sites: Vec<site::Site> = confs.iter().map(|c| site::Site::read(c)).collect();
    let width = sites.iter().map(|s| s.host.chars().count()).max().unwrap_or(0);

    for site in &sites {
        let php = site
            .fastcgi_port
            .map(|p| format!("php {p}"))
            .unwrap_or_else(|| "no fastcgi_pass".into());
        let root = site.root.as_deref().unwrap_or("no root directive");
        println!("  {:<width$}  {php:<10}  {root}", site.host);
    }
    println!("\n{} vhost(s) in {}", sites.len(), stack.rel(&stack.sites_dir()));
}
